seed_everything: 42

trainer:
  max_epochs: 20000
  accelerator: 'cuda'
  log_every_n_steps: 50
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: '/home/machine1/data/lightning_logs'
      name: 'CCNN_large_prop_model_params'
  devices: [ 0 ]

model:
  init_phase_generator:
    class_path: algorithms.backbone.DualNet.CCNN
    init_args:
      num_of_stages: 4
      input_dim_of_first_layer: 1
      output_dim_of_first_layer: 4
      output_channels: 1
  slm_phase_generator:
    class_path: algorithms.backbone.DualNet.CCNN
    init_args:
      num_of_stages: 3
      input_dim_of_first_layer: 1
      output_dim_of_first_layer: 4
      output_channels: 1
  #  wavelengths: [638e-9, 520e-9, 450e-9]
  wavelengths: [ 0.000520 ]
  pixel_size: 0.0036
  resolution: [ 1024, 2048 ]
  distances: [ 150 ]
  learning_rate: 1e-3
  num_of_frames: 1
  complex_model: true

data:
  data_dir: '/home/machine1/data/div2k'
  train_batch_size: 16
  val_batch_size: 16
  pred_batch_size: 16
  resolution: [ 1024, 2048 ]
  num_of_wavelengths: 1
  num_workers: 35